--------------------------------------------------------
--  File created - Sunday-January-28-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence EVENT_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EVENT_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence EVENT_USER_REPONSE_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EVENT_USER_REPONSE_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table EVENT
--------------------------------------------------------

  CREATE TABLE "EVENT" 
   (	"EVENT_ID" NUMBER DEFAULT "EVENT_ID_SEQ"."NEXTVAL", 
	"EVENT_NAME" VARCHAR2(100 BYTE), 
	"ORGANIZER_NAME" VARCHAR2(100 BYTE), 
	"ORGANIZER_EMAIL" VARCHAR2(100 BYTE), 
	"EVENT_SECRET" NUMBER, 
	"FINALIZED_RESPONSE" VARCHAR2(100 BYTE), 
	"SESSION_STATUS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table EVENT_USER_RESPONSE
--------------------------------------------------------

  CREATE TABLE "EVENT_USER_RESPONSE" 
   (	"EVENT_USER_RESPONSE_ID" NUMBER DEFAULT "EVENT_USER_REPONSE_ID_SEQ"."NEXTVAL", 
	"EVENT_EVENT_ID" NUMBER, 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"USER_EMAIL" VARCHAR2(100 BYTE), 
	"RESPONSE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE "EVENT" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "EVENT" MODIFY ("EVENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "EVENT" MODIFY ("ORGANIZER_NAME" NOT NULL ENABLE);
  ALTER TABLE "EVENT" MODIFY ("ORGANIZER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "EVENT" MODIFY ("EVENT_SECRET" NOT NULL ENABLE);
  ALTER TABLE "EVENT" MODIFY ("SESSION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "EVENT" ADD CONSTRAINT "EVENT_PK" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENT_USER_RESPONSE
--------------------------------------------------------

  ALTER TABLE "EVENT_USER_RESPONSE" MODIFY ("EVENT_USER_RESPONSE_ID" NOT NULL ENABLE);
  ALTER TABLE "EVENT_USER_RESPONSE" MODIFY ("EVENT_EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "EVENT_USER_RESPONSE" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "EVENT_USER_RESPONSE" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
