version: "3.9"
services:
    oracle-db-service:
        container_name: oracle-db-service-container
        ports:
            - '1521:1521'
        image: container-registry.oracle.com/database/express:21.3.0-xe
        environment:            
            ORACLE_SID: xe
            ORACLE_PWD: root
   